config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home", as: :home

  get   "itineraire",      to: "pages#itineraire", as: :itineraire

  get   "villes",          to: "villes#index", as: :list_ville
  get   "villes/new",      to: "villes#new", as: :new_ville
  post  "villes",          to: "villes#create"
  get   "villes/:id",      to: "villes#show", as: :ville
  get   "villes/:id/edit", to: "villes#edit", as: :edit_ville
  patch "villes/:id",      to: "villes#update"
  delete "villes/:id",     to: "villes#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ville.rb
class Ville < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def itineraire
    @villes = Ville.all
  end

  private

  def distance(loc1, loc2)
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg  # Delta, converted to rad
    dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    rm * c # Delta in meters
  end

end

app/controllers/villes_controller.rb
class VillesController < ApplicationController
  def index
    @villes = Ville.all
  end

  def new
    @ville = Ville.new
  end

  def show
    @ville = Ville.find(params[:id])
  end

  def create
    @ville = Ville.new(ville_params)
    if @ville.save
      redirect_to ville_path(@ville)
    end
  end

  def edit
    @ville = Ville.find(params[:id])
  end

  def update
    @ville = Ville.find(params[:id])
    @ville.update(ville_params)
    redirect_to ville_path(@ville)
  end

  def destroy
    @ville = Ville.find(params[:id])
    @ville.destroy
    redirect_to villes_path, status: :see_other
  end

  private

  def ville_params
    params.require(:ville).permit(:name, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Distance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Calcul de distance entre 2 villes</h2>
<h3>Menu</h3>
<%= link_to "Voir les villes", list_ville_path %>
<%= link_to "Ajouter une ville", new_ville_path %>
<%= link_to "Itineraire", itineraire_path %>

app/views/pages/itineraire.html.erb
<h2>Itineraire</h2>
<h3>Menu</h3>

<%= link_to "Retour", home_path %>

app/views/villes/edit.html.erb
<h3>Modifier une ville</h3>
<%= simple_form_for(@ville) do |ville| %>
  <%= ville.input :name, placeholder: "Ex: Paris" %>
  <%= ville.input :latitude %>
  <%= ville.input :longitude %>
  <%= ville.submit 'Modifier', class: 'btn-add'%>
<% end %>
<%= link_to "Retour", villes_path %>

app/views/villes/index.html.erb
<h2>Villes</h2>
<ol>
  <% @villes.each do |ville| %>
    <li><%= link_to ville.name, ville_path(ville) %></li>
  <% end %>
</ol>

<br>
<%= link_to "Ajouter une ville", new_ville_path %>
<%= link_to "Retour", home_path %>
<br>

app/views/villes/new.html.erb
<h3>Ajouter un ville</h3>
<%= simple_form_for(@ville) do |ville| %>
  <%= ville.input :name, placeholder: "Ex: Paris" %>
  <%= ville.input :latitude %>
  <%= ville.input :longitude %>
  <%= ville.submit 'Ajouter', class: 'btn-add'%>
<% end %>
<%= link_to "Retour", home_path %>

app/views/villes/show.html.erb
<h3><%= @ville.name.capitalize%></h3>
<p>Latitude: <%= @ville.latitude %></p>
<p>Longitude: <%= @ville.longitude %></p>

<%= link_to "Modifier", edit_ville_path %>
<%= link_to "Supprimer", ville_path(@ville), data: { turbo_method: :delete, turbo_confirm: "Confirmer-vous ?"} %>
<%= link_to "Retour", villes_path %>